# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import LockFactoryServerGrpc_pb2 as LockFactoryServerGrpc__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in LockFactoryServerGrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementServerStub(object):
    """*
    Service that defines management services for GRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.shutdownServer = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.ManagementServer/shutdownServer',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.isRunning = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.ManagementServer/isRunning',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)


class ManagementServerServicer(object):
    """*
    Service that defines management services for GRPC
    """

    def shutdownServer(self, request, context):
        """*
        Shutdowns the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def isRunning(self, request, context):
        """*
        Checks if it is runnning, returnning true if running
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'shutdownServer': grpc.unary_unary_rpc_method_handler(
                    servicer.shutdownServer,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'isRunning': grpc.unary_unary_rpc_method_handler(
                    servicer.isRunning,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.obapanel.lockfactoryserver.core.grpc.ManagementServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.obapanel.lockfactoryserver.core.grpc.ManagementServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManagementServer(object):
    """*
    Service that defines management services for GRPC
    """

    @staticmethod
    def shutdownServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.ManagementServer/shutdownServer',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def isRunning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.ManagementServer/isRunning',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LockServerStub(object):
    """*
    Service that makes a lock avalible
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.lock = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.LockServer/lock',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                _registered_method=True)
        self.tryLock = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.LockServer/tryLock',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                _registered_method=True)
        self.tryLockWithTimeOut = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.LockServer/tryLockWithTimeOut',
                request_serializer=LockFactoryServerGrpc__pb2.TryLockWithTimeout.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                _registered_method=True)
        self.lockStatus = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.LockServer/lockStatus',
                request_serializer=LockFactoryServerGrpc__pb2.NameTokenValues.SerializeToString,
                response_deserializer=LockFactoryServerGrpc__pb2.LockStatusValues.FromString,
                _registered_method=True)
        self.unLock = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.LockServer/unLock',
                request_serializer=LockFactoryServerGrpc__pb2.NameTokenValues.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.asyncLock = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.LockServer/asyncLock',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                _registered_method=True)


class LockServerServicer(object):
    """*
    Service that makes a lock avalible
    """

    def lock(self, request, context):
        """
        Try to obtain a lock, waiting if needed
        expects the name of the lock
        return a non-null non-empty string with the token of the lock when acquired
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryLock(self, request, context):
        """
        Try to obain a lock, without waiting
        expects name Name of the lock
        return a non-null non-empty string with the token of the lock if acquired, or an empty/null string if not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryLockWithTimeOut(self, request, context):
        """
        Try to obain a lock, waiting a defined time
        expects name Name of the lock, timeOut as wuantity of time to wait in milliseconds if timeUnit nor given
        or the timeUnit of the timeOut
        return a non-null non-empty string with the token of the lock if acquired, or an empty/null string if not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lockStatus(self, request, context):
        """
        Check if a lock is locked and how, status options are:
        -   ERROR: In case an error happens
        -   ABSENT: No lock has been found
        -   UNLOCKED: Lock exists and its unlocked
        -   OWNER: Lock exists, is locked by caller
        -   OTHER: Lock exists, is locked by other

        expects Name of the lock and the current token or null/empy if doesnt have one
        return LockStatus for current lock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unLock(self, request, context):
        """
        Unlock previously locked lock
        expects Name of the lock and obtained token when locking
        return true if lock exists and was unlocked by token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def asyncLock(self, request, context):
        """
        Try to obtain a lock, waiting the response if needed
        This is used in asynch clients
        expects the name of the lock
        return a non-null non-empty string with the token of the lock when acquired
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'lock': grpc.unary_unary_rpc_method_handler(
                    servicer.lock,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'tryLock': grpc.unary_unary_rpc_method_handler(
                    servicer.tryLock,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'tryLockWithTimeOut': grpc.unary_unary_rpc_method_handler(
                    servicer.tryLockWithTimeOut,
                    request_deserializer=LockFactoryServerGrpc__pb2.TryLockWithTimeout.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
            'lockStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.lockStatus,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameTokenValues.FromString,
                    response_serializer=LockFactoryServerGrpc__pb2.LockStatusValues.SerializeToString,
            ),
            'unLock': grpc.unary_unary_rpc_method_handler(
                    servicer.unLock,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameTokenValues.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'asyncLock': grpc.unary_unary_rpc_method_handler(
                    servicer.asyncLock,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.obapanel.lockfactoryserver.core.grpc.LockServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.obapanel.lockfactoryserver.core.grpc.LockServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockServer(object):
    """*
    Service that makes a lock avalible
    """

    @staticmethod
    def lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.LockServer/lock',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def tryLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.LockServer/tryLock',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def tryLockWithTimeOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.LockServer/tryLockWithTimeOut',
            LockFactoryServerGrpc__pb2.TryLockWithTimeout.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def lockStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.LockServer/lockStatus',
            LockFactoryServerGrpc__pb2.NameTokenValues.SerializeToString,
            LockFactoryServerGrpc__pb2.LockStatusValues.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.LockServer/unLock',
            LockFactoryServerGrpc__pb2.NameTokenValues.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def asyncLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.LockServer/asyncLock',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SemaphoreServerStub(object):
    """*
    Service that makes a semaphore avalible
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.currentPermits = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/currentPermits',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                _registered_method=True)
        self.acquire = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/acquire',
                request_serializer=LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.tryAcquire = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/tryAcquire',
                request_serializer=LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.tryAcquireWithTimeOut = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/tryAcquireWithTimeOut',
                request_serializer=LockFactoryServerGrpc__pb2.NamePermitsWithTimeout.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.release = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/release',
                request_serializer=LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.asyncAcquire = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/asyncAcquire',
                request_serializer=LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class SemaphoreServerServicer(object):
    """*
    Service that makes a semaphore avalible
    """

    def currentPermits(self, request, context):
        """
        Current permits of the semaphore
        requires name Name of the semaphore
        returns permits of the semaphore, zero if not exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def acquire(self, request, context):
        """
        Acquire N permits, waiting until acquired
        requires Semaphore name and number of permits to acquire
        @throws RemoteException if error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryAcquire(self, request, context):
        """
        Try to acquire N permits, without waiting
        requires Semaphore name and number of permits to acquire
        returns true if acquired, false if not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryAcquireWithTimeOut(self, request, context):
        """
        Wait a time to acquire N permits, returning if acquired ot time passed
        requires Semaphore name and number of permits to release and timeOut to wait until released or not, in milliseconds or other unit
        returns true if the permits have been released before the timeOut, false otherwise
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def release(self, request, context):
        """
        Release N permits from this semaphore
        requires Semaphore name and number of permits to release
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def asyncAcquire(self, request, context):
        """
        Acquire N permits, waiting asynchronously until acquired
        requires Semaphore name and number of permits to acquire
        @throws RemoteException if error
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemaphoreServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'currentPermits': grpc.unary_unary_rpc_method_handler(
                    servicer.currentPermits,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            ),
            'acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.acquire,
                    request_deserializer=LockFactoryServerGrpc__pb2.NamePermits.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'tryAcquire': grpc.unary_unary_rpc_method_handler(
                    servicer.tryAcquire,
                    request_deserializer=LockFactoryServerGrpc__pb2.NamePermits.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'tryAcquireWithTimeOut': grpc.unary_unary_rpc_method_handler(
                    servicer.tryAcquireWithTimeOut,
                    request_deserializer=LockFactoryServerGrpc__pb2.NamePermitsWithTimeout.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'release': grpc.unary_unary_rpc_method_handler(
                    servicer.release,
                    request_deserializer=LockFactoryServerGrpc__pb2.NamePermits.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'asyncAcquire': grpc.unary_unary_rpc_method_handler(
                    servicer.asyncAcquire,
                    request_deserializer=LockFactoryServerGrpc__pb2.NamePermits.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemaphoreServer(object):
    """*
    Service that makes a semaphore avalible
    """

    @staticmethod
    def currentPermits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/currentPermits',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/acquire',
            LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def tryAcquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/tryAcquire',
            LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def tryAcquireWithTimeOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/tryAcquireWithTimeOut',
            LockFactoryServerGrpc__pb2.NamePermitsWithTimeout.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def release(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/release',
            LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def asyncAcquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.SemaphoreServer/asyncAcquire',
            LockFactoryServerGrpc__pb2.NamePermits.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CountDownLatchServerStub(object):
    """*
    Service that makes a countdownlatch available
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createNew = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/createNew',
                request_serializer=LockFactoryServerGrpc__pb2.NameCount.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.countDown = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/countDown',
                request_serializer=LockFactoryServerGrpc__pb2.NameCount.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getCount = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/getCount',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
                _registered_method=True)
        self.awaitLatch = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/awaitLatch',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.tryAwaitWithTimeOut = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/tryAwaitWithTimeOut',
                request_serializer=LockFactoryServerGrpc__pb2.AwaitWithTimeout.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.asyncAwait = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/asyncAwait',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CountDownLatchServerServicer(object):
    """*
    Service that makes a countdownlatch available
    """

    def createNew(self, request, context):
        """
        Creates a new countDownLatch with the specified count
        requires Name of the countDownLatch and count to release
        returns true if created, false if already exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def countDown(self, request, context):
        """
        Decreases the count of the countDownLatch by 1
        requires Name of the countDownLatch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCount(self, request, context):
        """
        Get the current count
        requires Name of the countDownLatch
        returns current count of the countDownLatch, 0 if non existen
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def awaitLatch(self, request, context):
        """
        Await to the count to be zero
        requires name of the countDownLatch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryAwaitWithTimeOut(self, request, context):
        """*
        Waits until the timeOut time is consumed or the countDownlatch reaches zero
        requires Name of the countDownLatc, timeOut as time to wait and optionally timeUnit as unit of the timeOut; if not is milliseconds
        returns true if zero reached, false if time consumed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def asyncAwait(self, request, context):
        """
        Await to the count to be zero, responding asynchronoously
        requires name of the countDownLatch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CountDownLatchServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createNew': grpc.unary_unary_rpc_method_handler(
                    servicer.createNew,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameCount.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'countDown': grpc.unary_unary_rpc_method_handler(
                    servicer.countDown,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameCount.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getCount': grpc.unary_unary_rpc_method_handler(
                    servicer.getCount,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.Int32Value.SerializeToString,
            ),
            'awaitLatch': grpc.unary_unary_rpc_method_handler(
                    servicer.awaitLatch,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'tryAwaitWithTimeOut': grpc.unary_unary_rpc_method_handler(
                    servicer.tryAwaitWithTimeOut,
                    request_deserializer=LockFactoryServerGrpc__pb2.AwaitWithTimeout.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'asyncAwait': grpc.unary_unary_rpc_method_handler(
                    servicer.asyncAwait,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CountDownLatchServer(object):
    """*
    Service that makes a countdownlatch available
    """

    @staticmethod
    def createNew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/createNew',
            LockFactoryServerGrpc__pb2.NameCount.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def countDown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/countDown',
            LockFactoryServerGrpc__pb2.NameCount.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/getCount',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.Int32Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def awaitLatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/awaitLatch',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def tryAwaitWithTimeOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/tryAwaitWithTimeOut',
            LockFactoryServerGrpc__pb2.AwaitWithTimeout.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def asyncAwait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.CountDownLatchServer/asyncAwait',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HolderServerStub(object):
    """*
    Service that makes a holder available
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/get',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=LockFactoryServerGrpc__pb2.HolderResultGrpc.FromString,
                _registered_method=True)
        self.getWithTimeOut = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/getWithTimeOut',
                request_serializer=LockFactoryServerGrpc__pb2.HolderNameWithTimeOut.SerializeToString,
                response_deserializer=LockFactoryServerGrpc__pb2.HolderResultGrpc.FromString,
                _registered_method=True)
        self.getIfAvailable = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/getIfAvailable',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=LockFactoryServerGrpc__pb2.HolderResultGrpc.FromString,
                _registered_method=True)
        self.set = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/set',
                request_serializer=LockFactoryServerGrpc__pb2.HolderSet.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.setWithTimeToLive = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/setWithTimeToLive',
                request_serializer=LockFactoryServerGrpc__pb2.HolderSetWithTimeToLive.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.cancel = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/cancel',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class HolderServerServicer(object):
    """*
    Service that makes a holder available
    """

    def get(self, request, context):
        """
        Get value, await indefinitely
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWithTimeOut(self, request, context):
        """
        Get value, awaiting given time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getIfAvailable(self, request, context):
        """
        Get value if present, return not found if not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set(self, request, context):
        """
        Sets a value, holder is expired when the value is set
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setWithTimeToLive(self, request, context):
        """
        Sets a value, holder will expire in the time set
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def cancel(self, request, context):
        """
        Cancels a holder and expires and removes it
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HolderServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=LockFactoryServerGrpc__pb2.HolderResultGrpc.SerializeToString,
            ),
            'getWithTimeOut': grpc.unary_unary_rpc_method_handler(
                    servicer.getWithTimeOut,
                    request_deserializer=LockFactoryServerGrpc__pb2.HolderNameWithTimeOut.FromString,
                    response_serializer=LockFactoryServerGrpc__pb2.HolderResultGrpc.SerializeToString,
            ),
            'getIfAvailable': grpc.unary_unary_rpc_method_handler(
                    servicer.getIfAvailable,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=LockFactoryServerGrpc__pb2.HolderResultGrpc.SerializeToString,
            ),
            'set': grpc.unary_unary_rpc_method_handler(
                    servicer.set,
                    request_deserializer=LockFactoryServerGrpc__pb2.HolderSet.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'setWithTimeToLive': grpc.unary_unary_rpc_method_handler(
                    servicer.setWithTimeToLive,
                    request_deserializer=LockFactoryServerGrpc__pb2.HolderSetWithTimeToLive.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.obapanel.lockfactoryserver.core.grpc.HolderServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.obapanel.lockfactoryserver.core.grpc.HolderServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HolderServer(object):
    """*
    Service that makes a holder available
    """

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/get',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            LockFactoryServerGrpc__pb2.HolderResultGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getWithTimeOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/getWithTimeOut',
            LockFactoryServerGrpc__pb2.HolderNameWithTimeOut.SerializeToString,
            LockFactoryServerGrpc__pb2.HolderResultGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getIfAvailable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/getIfAvailable',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            LockFactoryServerGrpc__pb2.HolderResultGrpc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/set',
            LockFactoryServerGrpc__pb2.HolderSet.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setWithTimeToLive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/setWithTimeToLive',
            LockFactoryServerGrpc__pb2.HolderSetWithTimeToLive.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.HolderServer/cancel',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BucketRateLimiterStub(object):
    """*
    Service that makes a bucket rate limiter available and many request can try to consume permits
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.newRateLimiter = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/newRateLimiter',
                request_serializer=LockFactoryServerGrpc__pb2.BucketRateLimiterNew.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.getAvailableTokens = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/getAvailableTokens',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.FromString,
                _registered_method=True)
        self.tryConsume = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/tryConsume',
                request_serializer=LockFactoryServerGrpc__pb2.NameTokensConsume.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.tryConsumeWithTimeOut = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/tryConsumeWithTimeOut',
                request_serializer=LockFactoryServerGrpc__pb2.NameTokensConsumeWithTimeOut.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
                _registered_method=True)
        self.consume = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/consume',
                request_serializer=LockFactoryServerGrpc__pb2.NameTokensConsume.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.asyncConsume = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/asyncConsume',
                request_serializer=LockFactoryServerGrpc__pb2.NameTokensConsume.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.remove = channel.unary_unary(
                '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/remove',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class BucketRateLimiterServicer(object):
    """*
    Service that makes a bucket rate limiter available and many request can try to consume permits
    """

    def newRateLimiter(self, request, context):
        """
        Creates a new bucket rate limiter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAvailableTokens(self, request, context):
        """
        Get the actual available tokens, returns -1 if bucket doesn't exists, so this servers as an exists method
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryConsume(self, request, context):
        """
        Tries to get the numbered tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def tryConsumeWithTimeOut(self, request, context):
        """
        Tries to get the numbered tokens within the given time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def consume(self, request, context):
        """
        Get the number of tokens to consume, waiting until there are available
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def asyncConsume(self, request, context):
        """
        Get the number of tokens to consume, waiting until there are available, responding asynchronoously
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove(self, request, context):
        """
        Closes the limiter, nothing happens if it doesn't exist
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BucketRateLimiterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'newRateLimiter': grpc.unary_unary_rpc_method_handler(
                    servicer.newRateLimiter,
                    request_deserializer=LockFactoryServerGrpc__pb2.BucketRateLimiterNew.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'getAvailableTokens': grpc.unary_unary_rpc_method_handler(
                    servicer.getAvailableTokens,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.Int64Value.SerializeToString,
            ),
            'tryConsume': grpc.unary_unary_rpc_method_handler(
                    servicer.tryConsume,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameTokensConsume.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'tryConsumeWithTimeOut': grpc.unary_unary_rpc_method_handler(
                    servicer.tryConsumeWithTimeOut,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameTokensConsumeWithTimeOut.FromString,
                    response_serializer=google_dot_protobuf_dot_wrappers__pb2.BoolValue.SerializeToString,
            ),
            'consume': grpc.unary_unary_rpc_method_handler(
                    servicer.consume,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameTokensConsume.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'asyncConsume': grpc.unary_unary_rpc_method_handler(
                    servicer.asyncConsume,
                    request_deserializer=LockFactoryServerGrpc__pb2.NameTokensConsume.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'remove': grpc.unary_unary_rpc_method_handler(
                    servicer.remove,
                    request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BucketRateLimiter(object):
    """*
    Service that makes a bucket rate limiter available and many request can try to consume permits
    """

    @staticmethod
    def newRateLimiter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/newRateLimiter',
            LockFactoryServerGrpc__pb2.BucketRateLimiterNew.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAvailableTokens(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/getAvailableTokens',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.Int64Value.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def tryConsume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/tryConsume',
            LockFactoryServerGrpc__pb2.NameTokensConsume.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def tryConsumeWithTimeOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/tryConsumeWithTimeOut',
            LockFactoryServerGrpc__pb2.NameTokensConsumeWithTimeOut.SerializeToString,
            google_dot_protobuf_dot_wrappers__pb2.BoolValue.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def consume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/consume',
            LockFactoryServerGrpc__pb2.NameTokensConsume.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def asyncConsume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/asyncConsume',
            LockFactoryServerGrpc__pb2.NameTokensConsume.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/org.obapanel.lockfactoryserver.core.grpc.BucketRateLimiter/remove',
            google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
